[package]
name = "worker_dsp"
version = "0.0.1"
edition = "2021"

[dependencies]
redis = "0.23"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aws-config = "0.9"
aws-sdk-s3 = "0.9"
ebur128 = "0.2"
anyhow = "1.0"