[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./worker-dsp"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "always"
restartPolicyMaxRetries = 3
